# Generated by Django 5.0.3 on 2024-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_sell',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
